baseURL = ""
languageCode = "en"
title = "Seasides conference"

# Theme
theme = "owaspseasides"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = "UA-128895083-2"

[params]
    title = "Seasides InfoSec Conference 2022"
    date = "2019-11-01"
    description = "Seaside InfoSec Conference 2022 will be held on the 19th and 20th of August bringing you the opportunity to get an insight into the cyber security world."
    images = ["/images/social-share.jpg"]
    email = "admin@seasides.net"
    keywords = "security conference, seasides conference, infosec conference"
    copyright = "Made with Hugo & Devfest theme :heart:️"
    cfpUrl = ""
    subscriptionUrl = "https://seasides.net/sessions/"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "x"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

[menu]
[[menu.main]]
    identifier = "jobs"
    name = "Archive"
    url = "https://www.owaspseasides.com/"
    weight = 200
    external = true

[languages]
[languages.en]
    weight = 1
    languageName = "in"

[languages.fr]
    weight = 2
    languageName = "gb"



[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
